IF (DB_ID(N'Seminar1') IS NULL)
	CREATE DATABASE Seminar1
GO

USE Seminar1
GO

IF OBJECT_ID ('Products') IS NULL
	CREATE TABLE Products
	(
	Id INT NOT NULL IDENTITY(1, 1) CONSTRAINT PK_Product PRIMARY KEY,
	[Name] NVARCHAR(256) NOT NULL,
	[Description] NVARCHAR(2000) NOT NULL, 
	Price NUMERIC(20, 2) NOT NULL,
	IsAvailable BIT NOT NULL,
	ImagePath NVARCHAR(1000) NULL
	)
GO

IF OBJECT_ID ('Users') IS NULL
	CREATE TABLE Users
	(
	Id INT NOT NULL IDENTITY(1, 1) CONSTRAINT PK_User PRIMARY KEY,
	[UserName] NVARCHAR(256) NOT NULL,
	[Password] NVARCHAR(256) NOT NULL, 
	[SurName] NVARCHAR(256) NOT NULL,
	[Name] NVARCHAR(256) NOT NULL,
	LastLogin DATETIME NULL
	)
GO